[project]
name = "mldclean"
version = "0.1.0"
description = "CLI tool for ML data cleaning and inspection"
requires-python = ">=3.8"
dependencies = [
    "click>=8.0.0",
]

[project.scripts]
mldclean = "mldclean.cli:cli"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"